### ISSUE TITLE
Issue with Interop\Container\ContainerInterface

### ISSUE THREAD

**Issue by DesignyourCode** [dappur/framework#67]
Hi,

I am getting all sorts of issues when setting the project up from scratch. I tried to create this as a Vagrant file, and the PHPmyadmin worked, but I got an 403 forbidden for the frontend.
So I switched to setting up it without Vagrant and ended up with issues like the below:

```
Fatal error: Uncaught TypeError: Argument 1 passed to Dappur\Middleware\Middleware::__construct() must be an instance of Interop\Container\ContainerInterface, instance of Slim\Container given, called in /app/routes/admin-blog.php on line 98 and defined in /app/src/Middleware/Middleware.php:27 Stack trace: #0 /app/routes/admin-blog.php(98): Dappur\Middleware\Middleware->__construct(Object(Slim\Container)) #1 /vendor/slim/slim/Slim/RouteGroup.php(25): Closure->{closure}(Object(Slim\App)) #2 /vendor/slim/slim/Slim/App.php(272): Slim\RouteGroup->__invoke(Object(Slim\App)) #3 /app/routes/admin-blog.php(99): Slim\Ap in /app/src/Middleware/Middleware.php on line 27
```

Something doesn't seem right?

**Comment by edwardteach42** [comment]
This should be fixed in the latest v4.0 release
